### PR TITLE
Fix goldenspike.py to use DistToPointEvalutor

### PR DESCRIPTION
**Pull request by eacharles**
## Problem & Solution Description (including issue #)

#28 

## Code Quality
- [ ] My code follows [the code style of this project](https://rail-hub.readthedocs.io/en/latest/source/contributing.html#naming-conventions)
- [ ] I have written unit tests or justified all instances of `#pragma: no cover`; in the case of a bugfix, a new test that breaks as a result of the bug has been added
- [ ] My code contains relevant comments and necessary documentation for future maintainers; the change is reflected in applicable demos/tutorials (with output cleared!) and added/updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] Any breaking changes, described above, are accompanied by backwards compatibility and deprecation warnings

### CODE REVIEW

**Comment by ztq1996** [comment]
May I propose using the new evaluator? It is used in the goldenspike notebook in rail_hub

**Comment by eacharles** [comment]
It looks liek we have this:
for key, val in eval_dict.items():
    the_eval = DistToPointEvaluator.make_stage(name='dist_to_point', force_exact=True, **evaluator_stage_dict)
    result_dict[key] = the_eval.evaluate(val, truth)
    
1. Sure we can use that,
2. But we should change both to have name=f'dist_to_point_{key}', otherwise the output files will collide

**Comment by ztq1996** [comment]
Yeah, if that works.

**Review by sschmidt23 — APPROVED** [review]
looks good

**Pull request merged**
