### PR TITLE
Issue/375/introspection

### PR DESCRIPTION
**Pull request by eacharles**
Sorry sam

### CODE REVIEW

**Review by sschmidt23 — APPROVED** [review]
Looks good, and things appear to work,  only minor comment: the goldenspike.ipynb notebook has a final cell that says to just run cleanup.sh to delete all the temp files, but we did not include cleanup.sh in rail_pipelines/nb/examples/goldenspike, we could think about adding that back in here.

edit: one other comment: should we add a curl command to grab the example HSC data for the inform_all_hsc example?

**Comment by aimalz** [comment]
Tagging @OliviaLynn on this comment because I know she recently dealt with an accidental duplicate of the cleanup script and might have some insight on if it was (re)moved strategically as part of the bigger reorganization of the examples directory currently under way.

> Looks good, and things appear to work, only minor comment: the goldenspike.ipynb notebook has a final cell that says to just run cleanup.sh to delete all the temp files, but we did not include cleanup.sh in rail_pipelines/nb/examples/goldenspike, we could think about adding that back in here.
> 
> edit: one other comment: should we add a curl command to grab the example HSC data for the inform_all_hsc example?

(And while I'm here, re: edit, that sounds like a good idea to me!)

**Comment by eacharles** [comment]
The notebook is going to be moved to rail_hub in a PR coming along very soon.   Let's fix these issues there, once it is in it's final place.

**Comment by sschmidt23** [comment]
Ah, yes I forgot about the fact that these will move anyway, sorry, there was another earthquake at 3:30 am that woke me up  so not firing on all cylinders today.

**Pull request merged**
