### PR TITLE
Update smoke-test.yml to emit failures to slack channel

### PR DESCRIPTION
**Pull request by drewoldag**
This PR adds the functionality to emit smoke test failure message to the `pz-desc-rail-ci` slack channel.

### CODE REVIEW

**Comment by drewoldag** [comment]
The unit tests are failing for the same reason that the smoke tests have been failing. i.e. making these updates didn't trigger these test failures :)

**Review by sschmidt23 — APPROVED** [review]
Thanks Drew, looks good.

**Comment by sschmidt23** [comment]
I approved, though I won't merge in case @hangqianjun has additional comments.  Also, the test failing is obviously unrelated, I wasn't sure if we wanted to wait until the tests are once again passing (probably in a separate PR that we would have to merge into this branch) before merging.

**Comment by drewoldag** [comment]
I don't have a strong opinion about waiting vs. merging now. If we do merge now, then we'll start getting pings in the CI channel of course. I'll leave it up to you all to decide if that's considered annoying or helpful.

**Review by hangqianjun — APPROVED** [review]
Hi Thanks! Looks great I think we can merge it! (Sorry, I may have miscommunicated about the issue - I thought it is regarding to the evaluator failing in golden spike with the data handles, rather than the smoke test itself. But thanks so much for fixing this! It's much appretiated!!!)

**Pull request merged**
