### PR TITLE
Added blending pipeline to cli

### PR DESCRIPTION
**Pull request by eacharles**
## Code Quality
- [ ] My code follows [the code style of this project](https://rail-hub.readthedocs.io/en/latest/source/contributing.html#naming-conventions)
- [ ] I have written unit tests or justified all instances of `#pragma: no cover`; in the case of a bugfix, a new test that breaks as a result of the bug has been added
- [ ] My code contains relevant comments and necessary documentation for future maintainers; the change is reflected in applicable demos/tutorials (with output cleared!) and added/updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] Any breaking changes, described above, are accompanied by backwards compatibility and deprecation warnings

### CODE REVIEW

**Comment by sidneymau** [comment]
Not necessary for this PR, but there is a lot of reused boilerplate between some of these pipeline functions. For example, `blending_pipeline` is the same as `spectroscopic_selection_pipeline` with the exception of the `pipeline_name` , a `basename` argument, and the `spec_selection` loop. `truth_to_observed_pipeline` is similar as well

**Comment by sidneymau** [comment]
I would not be opposed to having the spectroscopic selection and blending pipelines be part of the truth_to_observed pipeline (especially because these pipelines are _part_ of what I would think of as being implied by "observed"). Are we using any of the intermediate catalogs produced, or was there a reason that the spec selection and blending scripts are not just extra toggles for `truth_to_observed`?

**Comment by eacharles** [comment]
Mostly that I'm not really sure about order of operations.   I think we want to run blending before we even to any selection, and we may want to run the spectroscopic stuff independently of the truth_to_observed.

**Review by sidneymau — APPROVED** [review]
Code looks good to me -- discussion about overall pipeline structure and the implementation thereof postponed for future issues

**Pull request merged**
